### ISSUE TITLE
Unable to run example Components

### ISSUE THREAD

**Issue by amsoftgroup** [openmpf/openmpf-cpp-component-sdk#82]
I'm hesitant to open an issue as it may likely be user error. However I've successfully built "openmpf-cpp-component-sdk" and successfully registered the .tar.gz in the OpenMPF web user interface.

I submit jobs to the resulting pipeline ( FrameDataComponent, GenericComponent, VideoCaptureComponent, etc.) but they hang on 0% complete. I presume I must register them as a node?

In the Node Config menu of the web UI, top right allows me to click a button "add node" but it states "all available nodes have already been configured". At the bottom left, "edit the number of services"  enumerates my newly deployed "openmpf-cpp-component-sdk" example (FrameDataComponent), but when I select it the algorithm it errors out and will not deploy.

I am monitoring docker "openmpf_workflow_manager" at /opt/mpf/share/logs/workflow_manager/log and it's not giving me anything to troubleshoot. Is there another log I should be looking at?

My environment:

CENTOS 7
uname -a : Linux workstation 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

git cloned from openmpf tag r4.1.0

any additional info you need pls let me know. Thanks!

**Comment by jrobble** [comment]
It seems that the Node Manager had an issue starting a C++ Component Executor process with your component library. Your code may have segfaulted or died for another reason. Try checking the following logs:

- node-manager.log
- node-manager-startup.log
- detection.log

The Node Manager is a Java process that runs on the host and only exists to receive messages from the Workflow Manager to start and stop component services, and to monitor those service processes.

The C++ Component Executor is the `amq_detection_component` process you see when you run `top`. You will see one instance of that process for each C++ component service that's running. That executor makes calls to your component library through the C++ Batch Component API. The executor logs output to detection.log. 

All of the executors on the same host use the same detection.log file. You may want to stop all other services through the Nodes UI and just run your service. That may make reading the logs easier.

We recommend getting your component code setup with a logger like our other components. If your code is segfaulting, you can add a bunch of debug log statements throughout your code to pinpoint which line is causing the problem.

**Comment by amsoftgroup** [comment]
Thanks for the debug info! I found the source of the problem but have not located where/why in the code or my particular environment it is happening. 

When I deploy "HelloWorld.tar.gz" via workflow manager web application, it appears to get properly deployed to the workflow docker container. The HelloWorld.tar.gz file is copied to /opt/mpf/share/components, and is unzipped in /opt/mpf/plugins.

In the Node Manager Docker container, HelloWorld.tar.gz is copied to /opt/mpf/share/components, but it is not unzipped to /opt/mpf/plugins. **Manually unzipping the HelloWorld.tar.gz in the folder /opt/mpf/plugins on the Node Manager Docker container appears to fix my problem**. 

I'll continue to investigate my root cause.

**Comment by jrobble** [comment]
Sorry for the trouble. This is a known issue and expected behavior. In the [Release Notes](https://openmpf.github.io/docs/site/Release-Notes/index.html#openmpf-300-december-2018):

> NOTE: Do not attempt to register or unregister a component through the Nodes UI in a Docker deployment. It may appear to succeed, but the changes will not affect the child Node Manager containers, only the Workflow Manager container. Also, do not attempt to use the mpf command line tools in a Docker deployment.

Starting with Release 3.0.0, we've begun transitioning to Docker. At the end of Release 5.0.0 (which is in progress) we hope to complete the transition. That said, the current Release 4.1.0 is in an intermediary state where we've separated the Workflow Manager image from the components, but have yet to fully Dockerize each component into a microservice image. Instead, most of the components (with the exception of EAST, which is our first microservice), are part of the Node Manager image. 

Attempting to register a component through the web UI will only make the Workflow Manager aware of it, but not actually deploy it on the Node Manager image. We decided that since the Node Manager image will be going away, that we should not focus on addressing this issue.

At the end of Release 5.0.0, you should be able to run a separate Docker container for each OpenMPF component service instance, and that will automatically register with the Workflow Manager container through the REST API. There will be no Node Manager container. Actually, the Node Manager will not be used at all for a Docker deployment.
